
trigger:
- feature/pipeline

pool: 
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: jtqcr.azurecr.io
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: 'angular/Dockerfile'