
trigger:
- feature/pipeline

pool: 
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloudserv'
    organization: 'timothepaty'
    scannerMode: 'Other'
    extraProperties: |
      sonar.projectKey=timothepaty_jtqj
      sonar.projectName=jtqj
- task: Maven@4
  inputs:
    mavenPomFile: 'java/jtqj/pom.xml'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'pom'

- script: |
    cd java/jtqj
    mvn install
  displayName: 'mvn install'

- script: | 
    cd java/jtqj
    mvn test
  displayName: 'Test'

- task: SonarCloudAnalyze@1
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'