
trigger:
- feature/pipeline

pool: 
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0

- task: NodeTool@0
  inputs:
    versionSpec: '20.11.1'
  displayName: 'Install Node.js'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloudserv'
    organization: 'timothepaty'
    scannerMode: 'CLI'
    configMode: 'file'

- script: |
    npm install -g @angular/cli
    cd angular
    npm install --global yarn
    yarn install --force
    npm run build
  displayName: 'npm install and build'

- script: |
    cd angular
    yarn test-headless
  displayName: 'Test'

- task: SonarCloudAnalyze@1
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'