apiVersion: v1
kind: Service
metadata:
  name: angular-service
  namespace: flux-system
spec:
  type: NodePort
  selector:
    name: angular-app
    app: angular-app
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30081
