
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: flux-system
spec:
  type: ClusterIP
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
