name: CI Build & test for angular
on: [push, pull_request]
jobs:
  build:
    if: ${{github.repository == 'Szhao52/jump-the-queue'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: build 
        run: |
          cd angular
          yarn install --force
          npm run build
      - name: Test code
        run: yarn test-headless
