name: CI Build & Test Springboot
on: [push, pull_request]
jobs:
  build:
    if: ${{github.repository == 'SZhao52/jump-the-queue'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build project with Maven
        run: |
          cd java/jtqj
          mvn install
      - name: Test project with Maven
        run: |
          cd java/jtqj
          mvn test
      - name: Sonar Scanner
        run:  mvn -B verify sonar:sonar -Dsonar.projectKey=jump-the-queue -Dsonar.organization=szhao52 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN"
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
