name: Build and Push Dockerfile
on: [push, pull_request]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: szhao52/jump-the-queue #problems with uppercase
  IMAGE_TAG: ${{ github.run_number }} #same as $BUILD_NUMBER in jenkins

jobs: 
  build:
    if: ${{github.repository == 'Szhao52/jump-the-queue'}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: ./angular/Dockerfile
            image: ghrcr.io/szhao52/jtq-angular
          - dockerfile: ./java/jtqj/Dockerfile
            image: ghrcr.io/szhao52/jtq-springboot 
          - path: ./angular
          - path: ./java/jtqj    
    permissions:
      contents: read
      packages: write 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ matrix.image }} 
      
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}