name: Build and Push Dockerfile
on: [push, pull_request]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: szhao52/jump-the-queue #problems with uppercase

jobs: 
  build:
    if: ${{github.repository == 'Szhao52/jump-the-queue'}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: ./angular
            dockerfile: ./angular/Dockerfile
            image_suffix: angular-app
          - context: ./java/jtqj           
            dockerfile: ./java/jtqj/Dockerfile
            image_suffix: springboot-app
    permissions:
      contents: read
      packages: write 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.image_suffix }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}